title: Planetary Computer APIs Function packages and Helm charts
description: This site stores Function package zip files and Helm chart tarballs for the Planteary Computer APIs
theme: minima
url: "https://microsoft.github.io/planetary-computer-apis"
repo_name: planetary-computer-apis

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
