services:
  dqe-dev:
    image: pc-query-dataapi-dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: dqe/Dockerfile.dev
      args:
        DQE_IMAGE_NAME: pc-query-dataapi
    environment:
      - ENVIRONMENT=development
      - FF_VRT="yes"
      - STAC_API_URL=http://mqe:8081
      - STAC_API_HREF=http://localhost:8080/stac/

      # titiler.pgstac
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=database
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - WEB_CONCURRENCY=1
      - WORKERS_PER_CORE=1
    volumes:
      - .:/opt/src
    command: >
      /bin/bash
    depends_on:
      - mqe
      - dqe
  mqe-dev:
    image: pc-query-stacapi-dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: mqe/Dockerfile.dev
      args:
        MQE_IMAGE_NAME: pc-query-stacapi
    environment:
      - ENVIRONMENT=development
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=database
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
    volumes:
      - .:/opt/src
    command: >
      /bin/bash
    depends_on:
      - mqe
  sas-dev:
    image: ${SAS_IMAGE_NAME}-dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: sas/Dockerfile.dev
      args:
        SAS_IMAGE_NAME: ${SAS_IMAGE_NAME}
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/opt/src
    command: >
      /bin/bash
    depends_on:
      - sas
