services:
  stac:
    image: pc-apis-stac
    build:
      context: .
      dockerfile: pcstac/Dockerfile
    environment:
      - APP_ROOT_PATH=/stac
      - APP_HOST=0.0.0.0
      - APP_PORT=8081
      - FORWARDED_ALLOW_IPS=*
      - ENVIRONMENT=local
      - PCAPIS_DEBUG=TRUE
      - TILER_HREF=http://localhost:8080/data/

      # Azure Storage
      - PCAPIS_COLLECTION_CONFIG__ACCOUNT_URL=http://azurite:10002/devstoreaccount1
      - PCAPIS_COLLECTION_CONFIG__ACCOUNT_NAME=devstoreaccount1
      - PCAPIS_COLLECTION_CONFIG__ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - PCAPIS_COLLECTION_CONFIG__TABLE_NAME=collectionconfig

      - PCAPIS_CONTAINER_CONFIG__ACCOUNT_URL=http://azurite:10002/devstoreaccount1
      - PCAPIS_CONTAINER_CONFIG__ACCOUNT_NAME=devstoreaccount1
      - PCAPIS_CONTAINER_CONFIG__ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - PCAPIS_CONTAINER_CONFIG__TABLE_NAME=containerconfig

      # Redis
      - PCAPIS_REDIS_HOSTNAME=redis
      - PCAPIS_REDIS_PASSWORD=devcache
      - PCAPIS_REDIS_PORT=6380
      - PCAPIS_REDIS_SSL=FALSE

      # Rate limit
      - PCAPIS_RATE_LIMITS__COLLECTIONS=10
      - PCAPIS_RATE_LIMITS__COLLECTION=10
      - PCAPIS_RATE_LIMITS__ITEMS=10
      - PCAPIS_RATE_LIMITS__ITEM=10
      - PCAPIS_RATE_LIMITS__SEARCH=10

      # Used by pgstac backend
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432

      # Used by pypgstac migrate
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=database
      - PGDATABASE=postgis

      # Used for logging and metrics
      - APP_INSIGHTS_INSTRUMENTATION_KEY
    ports:
      - "8081:8081"
    volumes:
      - ./pccommon:/opt/src/pccommon
      - ./pcstac:/opt/src/pcstac
    depends_on:
      - database
    command: >
      bash -c "pypgstac pgready && uvicorn pcstac.main:app --host 0.0.0.0 --port 8081 --reload --proxy-headers"
  tiler:
    image: pc-apis-tiler
    # For Mac OS M1 user, you'll need to add `platform: linux/amd64`.
    # see https://github.com/developmentseed/titiler/discussions/387#discussioncomment-1643110
    # platform: linux/amd64
    build:
      context: .
      dockerfile: pctiler/Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./pctiler:/opt/src/pctiler
      - ./pctiler/templates:/opt/src/templates
      - ./pccommon:/opt/src/pccommon
    environment:
      - APP_ROOT_PATH=/data
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - CPL_DEBUG=ON
      - FORWARDED_ALLOW_IPS=*
      - FF_VRT="yes"
      - STAC_API_URL=http://stac:8081
      - STAC_API_HREF=http://localhost:8080/stac/
      - PC_SDK_SAS_URL=https://planetarycomputer-staging.microsoft.com/api/sas/v1/token

      # titiler.pgstac
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=database
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
      - WEB_CONCURRENCY=1
      - WORKERS_PER_CORE=1

      # Azure Storage
      - PCAPIS_COLLECTION_CONFIG__ACCOUNT_URL=http://azurite:10002/devstoreaccount1
      - PCAPIS_COLLECTION_CONFIG__ACCOUNT_NAME=devstoreaccount1
      - PCAPIS_COLLECTION_CONFIG__ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - PCAPIS_COLLECTION_CONFIG__TABLE_NAME=collectionconfig

      - PCAPIS_CONTAINER_CONFIG__ACCOUNT_URL=http://azurite:10002/devstoreaccount1
      - PCAPIS_CONTAINER_CONFIG__ACCOUNT_NAME=devstoreaccount1
      - PCAPIS_CONTAINER_CONFIG__ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - PCAPIS_CONTAINER_CONFIG__TABLE_NAME=containerconfig

      # Redis
      - PCAPIS_REDIS_HOSTNAME=redis
      - PCAPIS_REDIS_PASSWORD=devcache
      - PCAPIS_REDIS_PORT=6380
      - PCAPIS_REDIS_SSL=FALSE

      # Used for logging and metrics
      - APP_INSIGHTS_INSTRUMENTATION_KEY
    depends_on:
      - database
    command: [ "uvicorn", "pctiler.main:app", "--host", "0.0.0.0", "--port", "8082", "--reload", "--proxy-headers" ]
  nginx:
    image: pc-apis-nginx
    container_name: pc-apis-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - stac
      - tiler
    depends_on:
      - tiler
      - stac
    volumes:
      - ./nginx/etc/nginx:/etc/nginx
    ports:
      - 8080:80
  database:
    container_name: pc-stac-db
    image: pc-apis-stac-db
    build:
      context: ./pgstac
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5432:5432"
    volumes:
      - pc-apis-pgdata:/var/lib/postgresql/data
  azurite:
    container_name: pcapis-azurite
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    command: "azurite --silent --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost
      0.0.0.0 -l /workspace"
    ports:
      - "10000:10000" # Blob
      - "10001:10001" # Queue
      - "10002:10002" # Table
    volumes:
      - pc-apis-azurite-data:/workspace
  redis:
    image: redis:6.2.6-buster
    command: redis-server --port 6380 --requirepass devcache
    ports:
     - "6380:6380"
    volumes:
      - pc-apis-redis-data:/data

volumes:
  pc-apis-pgdata:
  pc-apis-azurite-data:
  pc-apis-redis-data:
networks:
  default:
    name: pc-apis-dev-network
