{{- if .Values.migrations.enabled -}}
# We're no longer handling migration in the PQE
# and instead handling it in ETL.
# This is not maintained or tested for PGSTAC.
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mqe.fullname" . }}-{{ .Release.Revision }}
  labels:
    {{- include "mqe.labels" . | nindent 4 }}
  {{- with .Values.migrations.job.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "mqe.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
        command: ["pypgstac", "migrate"]
        env:
        - name: PGUSER
          value: "{{ .Values.postgres.user }}"
        - name: PGPASSWORD
          value: "{{ .Values.postgres.password }}"
        - name: PGDATABASE
          value: "{{ .Values.postgres.dbName }}"
        - name: PGPORT
          value: "{{ .Values.postgres.port }}"
        - name: PGHOST
          value: "{{ .Values.postgres.serverName }}"
        - name: ENVIRONMENT
          value: "{{ .Values.environment }}"
      restartPolicy: {{ .Values.migrations.job.restartPolicy }}
{{- end }}