name: base
channels:
  - conda-forge
dependencies:
  - python=3.9.16
  - pystac==1.7.1
  - jinja2==3.0.3
  - rasterio==1.3.6
  - pyproj==3.4.1
  - planetary-computer==0.4.9
  - geojson-pydantic==0.4.2
  # colormap dependencies
  - matplotlib-base==3.4.3
  - pip
  - pip:
      - "titiler.core==0.10.2"
      - "titiler.mosaic==0.10.2"

      -  # titiler-pgstac
      - "psycopg[binary,pool]"
      - "titiler.pgstac==0.2.4"
