apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pctiler.fullname" . }}
  labels:
    {{- include "pctiler.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pctiler.fullname" . }}
  minReplicas: {{ .Values.tiler.hpa.minReplicas }}
  maxReplicas: {{ .Values.tiler.hpa.maxReplicas }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_requests_per_minute
      target:
        type: AverageValue
        averageValue: 500m