services:
  deploy:
    container_name: pc-apis-deploy
    image: pc-apis-deploy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - IMAGE_TAG
      - GIT_COMMIT

      - ARM_SUBSCRIPTION_ID
      - ARM_TENANT_ID
      - ARM_CLIENT_ID
      - ARM_CLIENT_SECRET

      # Used in the dev stack as an identifier
      - TF_VAR_username=${USER}
    volumes:
      - .:/opt/src
