services:
  deploy:
    container_name: pc-apis-deploy
    image: pc-apis-deploy
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    environment:
      - ACR_STAC_REPO=${ACR_STAC_REPO:-mcr.microsoft.com/planetary-computer-apis/stac}
      - ACR_TILER_REPO=${ACR_TILER_REPO:-mcr.microsoft.com/planetary-computer-apis/tiler}
      - IMAGE_TAG
      - GIT_COMMIT

      - ARM_SUBSCRIPTION_ID
      - ARM_TENANT_ID
      - ARM_CLIENT_ID
      - ARM_CLIENT_SECRET

      # Used in the dev stack as an identifier
      - TF_VAR_username=${USER}
    working_dir: /opt/src/deployment
    volumes:
      - ../deployment:/opt/src/deployment
      - ../pccommon:/opt/src/pccommon:ro
      - ../pcfuncs:/opt/src/pcfuncs:ro
