services:
  deploy:
    container_name: pc-mqe-deploy
    image: pc-mqe-deploy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - IMAGE_TAG=${IMAGE_TAG}
      - GIT_COMMIT=${GIT_COMMIT}

      - ARM_SUBSCRIPTION_ID=${subscriptionId}
      - ARM_TENANT_ID=${tenantId}
      - ARM_CLIENT_ID=${servicePrincipalId}
      - ARM_CLIENT_SECRET=${servicePrincipalKey}

      # Used in the dev stack as an identifier
      - TF_VAR_username=${USER}
    volumes:
      - .:/opt/src
