services:
  deploy:
    container_name: pc-mqe-deploy
    image: pc-mqe-deploy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # For Terraform
      - TF_VAR_username=${USER}
      - ARM_SUBSCRIPTION_ID=${subscriptionId}
      - ARM_TENANT_ID=${tenantId}
      - ARM_CLIENT_ID=${servicePrincipalId}
      - ARM_CLIENT_SECRET=${servicePrincipalKey}

      # For Azure CLI
      - AZURE_TENANT_ID=${tenantId}
      - AZURE_CLIENT_ID=${servicePrincipalId}
      - AZURE_CLIENT_SECRET=${servicePrincipalKey}

      # For deployment
      - MQE_IMAGE_NAME=${MQE_IMAGE_NAME}
      - DQE_IMAGE_NAME=${DQE_IMAGE_NAME}
      - SAS_IMAGE_NAME=${SAS_IMAGE_NAME}
      - MIGRATIONS_IMAGE_NAME=${MIGRATIONS_IMAGE_NAME}
      - IMAGE_TAG=${IMAGE_TAG}
      - GIT_COMMIT=${GIT_COMMIT}
    volumes:
      - .:/opt/src
