services:
  deploy:
    container_name: pc-mqe-deploy
    image: pc-mqe-deploy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # For Terraform
      - TF_VAR_username=${USER}
      - ARM_SUBSCRIPTION_ID
      - ARM_TENANT_ID
      - ARM_CLIENT_ID
      - ARM_CLIENT_SECRET
