environment: "staging"

tiler:
  enabled: true
  image:
    # e.g. myacr.azurecr.io/my-repository
    repository: ""
    pullPolicy: Always
    tag: "latest"

  server:
    minDbConnections: "1"
    maxDbConnections: "1"
    webConcurrency: "1"
    request_timeout: 30

  service:
    type: ClusterIP
    port: 80
    annotations: {}

  deploy:
    replicaCount: 10
    podAnnotations: {}
    imagePullSecrets: []
    securityContext: {}
    podSecurityContext: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling:
      enabled: false
    useWorkloadIdentity: false
    serviceAccount:
      annotations: {}

  stac_api_url: ""
  stac_api_href: ""
  pc_sdk_sas_url: ""
  pc_sdk_subscription_key: ""
  vectortile_sa_base_url: ""

  default_max_items_per_tile: 5
  host: "0.0.0.0"
  port: "80"
  appRootPath: ""

storage:
  account_name: ""
  account_key: ""
  collection_config_table_name: ""
  container_config_table_name: ""
  ip_exception_config_table_name: ""
  table_value_ttl: 600

redis:
  host: ""
  password: ""
  port: 6380
  ssl: true
  ttl: 600

postgres:
  serverName: ""
  user: ""
  password: ""
  dbName: "postgis"
  port: "5432"

metrics:
  instrumentationKey: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

nameOverride: ""
fullnameOverride: ""
