name: PQE Tests

on:
  push:
    branches: [ $default-branch ]
    tags: [ v* ]
  pull_request:
    branches: [ $default-branch, cicd-target ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build containers and bring them up for testing
      run: ./scripts/setup
    - name: Run tests
      run: ./scripts/test
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Add MQE image tags
        uses: docker/metadata-action@v3
        id: add-mqe-image-tags
        with:
          images: |
            ghcr.io/microsoft/pc-query-stacapi
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Add DQE image tags
        uses: docker/metadata-action@v3
        id: add-dqe-image-tags
        with:
          images: |
            ghcr.io/microsoft/pc-query-dataapi
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish MQE image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.add-mqe-image-tags.outputs.tags }}
          labels: ${{ steps.add-mqe-image-tags.outputs.labels }}
      - name: Build and publish DQE image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.add-dqe-image-tags.outputs.tags }}
          labels: ${{ steps.add-dqe-image-tags.outputs.labels }}