name: PQE Tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build containers and bring them up for testing
      run: ./scripts/setup
    - name: Run tests
      run: ./scripts/test
